scriptencoding utf-8

if v:progname == 'vi'
    set noloadplugins                 " don't load plugins when launching vi
endif

" {{{ plugins
if &loadplugins
    if has('packages')
        packadd! vim-repeat
        packadd! vim-unimpaired
        packadd! vim-commentary
        packadd! vim-surround
        packadd! vim-dispatch
    endif
endif
" }}}
