scriptencoding utf-8

if v:progname == 'vi'
    set noloadplugins                 " don't load plugins when launching vi
endif

" {{{ plugins
if &loadplugins
    if has('packages')
        packadd! vim-repeat
        packadd! vim-unimpaired
        packadd! vim-commentary
        packadd! vim-surround
        packadd! vim-dispatch
        packadd! vim-dirvish

        " colors and syntax stuff
        packadd! base16-vim
    else
        source $HOME/.vim/pack/bundle/opt/vim-pathogen/pathogen.vim
        call pathogen#infect('pack/bundle/opt/{}')
    endif
endif
" }}}

" Must come *after* the `:packadd!` calls above otherwise the contents of
" package "ftdetect" directories won't be evaluated.
filetype indent plugin on
syntax on
